import { configFromEnv, loadEnvironment } from './config.js';
import { createApp } from './app.js';
import { LocalCare } from './local-care.js';
import { LocalSpeech } from './local-speech.js';
import { PlanStore, defaultPlanPath } from './chatgpt-plan/storage.js';
import { PlanReasoner } from './plan-reasoner.js';
import { ConversationService } from './conversation.js';
loadEnvironment();
const config = configFromEnv();
const care = config.databaseUrl ? new LocalCare({ connectionString: config.databaseUrl }) : undefined;
const reasoner = config.sessionKey && config.planUserId ? new PlanReasoner(new PlanStore(defaultPlanPath, config.sessionKey)) : undefined;
const speech = config.voiceTransport === 'local' && care && reasoner && await reasoner.available() ? new LocalSpeech() : undefined;
const conversation = speech && care && reasoner ? new ConversationService(care, reasoner, config.planUserId!, undefined, (text, signal) => speech.synthesize(text, signal)) : undefined;
const app = await createApp(config, { care, speech, conversation });
if (speech) await speech.primeNavigation().catch(() => { console.error('Local speech could not become ready. Touch remains available.'); });
await app.listen({ host: '127.0.0.1', port: config.port });
console.log(`Nancy is running at ${config.origin}. Cloud readiness: /api/config`);
for (const signal of ['SIGINT', 'SIGTERM'] as const) process.once(signal, () => { void app.close().then(() => process.exit(0)); });
